# Generated by Django 5.0.6 on 2024-10-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
