# Generated by Django 5.0.6 on 2024-10-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_productopedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='producto',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
    ]
