# Generated by Django 5.0.6 on 2024-10-20 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_pedidos_producto_alter_pedidos_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
