# Generated by Django 5.0.6 on 2024-10-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productopedido_fecha_productopedido_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopedido',
            name='nombre',
        ),
    ]
