# Generated by Django 5.0.6 on 2024-10-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_productopedido_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='tipo_pago',
        ),
    ]
