# Generated by Django 5.0.6 on 2024-10-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pedidos_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='tipo_pago',
            field=models.CharField(max_length=50),
        ),
    ]
